on:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
  release:
    types:
      - created

name: Publish NPM package
jobs:
  install:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: npm ci
        run: npm ci
      - name: build
        run: make build
      - name: test
        run: make test bench

      - name: Publish
        uses: menduz/oddish-action@master
        with:
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
